### ISSUE TITLE
Тоже не собирается

### ISSUE THREAD

**Issue by fedor129397** [fandrej/glonassd#3]
Никаких ide нет и прав на запись достаточно (как вы предположили здесь: https://github.com/fandrej/glonassd/issues/1), ubuntu server, командная строка.

Пробовал gcc 4.8 и 4.9.3 (ну, не смог я найти 4.9.2 как у вас) - там все еще более плохо.

lsb_release -a

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.1 LTS
> Release:        18.04
> Codename:       bionic

gcc -v

> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1 18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

make all

> gcc -std=gnu99 -D_REENTERANT -m64 -O2 -flto -g0 -I/usr/include/nptl -I/usr/include/postgresql -lpq -lpthread -L/usr/lib/nptl -rdynamic -ldl -lrt -lm glonassd.c loadconfig.c todaemon.c logger.c worker.c lib.c forwarder.c -o glonassd
> glonassd.c: In function ‘parceParams’:
> glonassd.c:148:3: warning: ignoring return value of ‘getcwd’, declared with attribute warn_unused_result [-Wunused-result]
>    getcwd(stParams.start_path, FILENAME_MAX);
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> todaemon.c: In function ‘toDaemon’:
> todaemon.c:76:2: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
>   chdir("/");    // stParams.start_path
>   ^~~~~~~~~~
> todaemon.c:89:2: warning: ignoring return value of ‘dup’, declared with attribute warn_unused_result [-Wunused-result]
>   dup(tmp); /* fd 1 = stdout */
>   ^~~~~~~~
> todaemon.c:90:2: warning: ignoring return value of ‘dup’, declared with attribute warn_unused_result [-Wunused-result]
>   dup(tmp); /* fd 2 = stderr */
>   ^~~~~~~~
> logger.c: In function ‘logging’:
> logger.c:49:22: warning: format not a string literal and no format arguments [-Wformat-security]
>    syslog(LOG_NOTICE, message);
>                       ^~~~~~~
> logger.c:53:23: warning: format not a string literal and no format arguments [-Wformat-security]
>     syslog(LOG_NOTICE, message);
>                        ^~~~~~~
> lib.c: In function ‘log2file’:
> lib.c:325:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>     write(fHandle, content, content_size);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> forwarder.c: In function ‘data_save’:
> forwarder.c:130:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>     write(fHandle, &msg, sizeof(ST_FORWARD_MSG));
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> forwarder.c:132:4: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>     write(fHandle, content, content_size);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In function ‘open’,
>     inlined from ‘log2file.part.0’ at lib.c:324:5:
> /usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
>     __open_missing_mode ();
>     ^
> lto-wrapper: fatal error: gcc returned 1 exit status
> compilation terminated.
> /usr/bin/ld: error: lto-wrapper failed
> collect2: error: ld returned 1 exit status
> Makefile:19: recipe for target 'glonassd' failed
> make: *** [glonassd] Error 1

**Comment by fandrej** [comment]
cd ~/temp/glonassd

andrey@locman:~/temp/glonassd$ gcc -v
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

```

andrey@locman:~/temp/glonassd$ make all
```
gcc -std=gnu99 -D_REENTERANT -m64 -O2 -flto -g0 -I/usr/include/nptl glonassd.c loadconfig.c todaemon.c logger.c worker.c lib.c forwarder.c -lpthread -L/usr/lib/nptl -rdynamic -ldl -lrt -lm -o glonassd
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 galileo.c -o galileo.o
gcc -shared -o galileo.so galileo.o
rm galileo.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 satlite.c -o satlite.o
gcc -shared -o satlite.so satlite.o
rm satlite.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 wialonips.c -o wialonips.o
gcc -shared -o wialonips.so wialonips.o
rm wialonips.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 gps103.c -o gps103.o
gcc -shared -o gps103.so gps103.o
rm gps103.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 soap.c -o soap.o
gcc -shared -o soap.so soap.o
rm soap.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 egts.c -o egts.o
gcc -shared -o egts.so egts.o
rm egts.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 arnavi.c -o arnavi.o
gcc -shared -o arnavi.so arnavi.o
rm arnavi.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 arnavi5.c -o arnavi5.o
gcc -shared -o arnavi5.so arnavi5.o
rm arnavi5.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 favw.c -o favw.o
gcc -shared -o favw.so favw.o
rm favw.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 fava.c -o fava.o
gcc -shared -o fava.so fava.o
rm fava.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 prototest.c -o prototest.o
gcc -shared -o prototest.so prototest.o
rm prototest.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 -I/usr/include/nptl -I/usr/include/postgresql pg.c -lpthread -L/usr/lib/nptl -rdynamic -ldl -lrt -lm -o pg.o -lpq
gcc -shared -o pg.so pg.o -lpq
rm pg.o
gcc -c -std=gnu99 -D_REENTERANT -m64 -fpic -Wall -O2 -flto -g0 -I/usr/include/nptl -I/usr/local/include/hiredis rds.c -I/usr/local/include/json-c/ -lpthread -L/usr/lib/nptl -rdynamic -ldl -lrt -lm -o rds.o -lhiredis -ljson-c
gcc -shared -o rds.so rds.o -lhiredis
rm rds.o
```

**Comment by fandrej** [comment]
Makefile
```
PROJECT = glonassd

CC = gcc
LIBS = -lpthread -L/usr/lib/nptl -rdynamic -ldl -lrt -lm
INCLUDE = -I/usr/include/nptl
# https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html#Option-Summary
CFLAGS = -std=gnu99 -D_REENTERANT -m64
SOCFLAGS = -std=gnu99 -D_REENTERANT -m64 -fpic -Wall
# https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
OPTIMIZE = -O2 -flto -g0
#OPTIMIZE = -O0 -flto -g -fno-stack-protector
# https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html#Debugging-Options
DEBUG = -g

SOURCE = glonassd.c loadconfig.c todaemon.c logger.c worker.c lib.c forwarder.c

HEADERS = $(wildcard *.h)

# ATTENTION: $(LIBS) MUST BE AFTER $(SOURCE) !!!

$(PROJECT): $(SOURCE) $(HEADERS)
	$(CC) $(CFLAGS) $(OPTIMIZE) $(INCLUDE) $(SOURCE) $(LIBS) -o $(PROJECT)

run: $(PROJECT)
	./$(PROJECT) start

# shared library for decode/encode GALILEO
galileo: galileo.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) galileo.c -o galileo.o
	$(CC) -shared -o galileo.so galileo.o
	rm galileo.o

# shared library for decode/encode SAT-LITE/SAT-LITE2
satlite: satlite.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) satlite.c -o satlite.o
	$(CC) -shared -o satlite.so satlite.o
	rm satlite.o

# shared library for decode/encode ARNAVI 4
arnavi: arnavi.c arnavi.h de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) arnavi.c -o arnavi.o
	$(CC) -shared -o arnavi.so arnavi.o
	rm arnavi.o

# shared library for decode/encode ARNAVI 5
arnavi5: arnavi5.c arnavi.h de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) arnavi5.c -o arnavi5.o
	$(CC) -shared -o arnavi5.so arnavi5.o
	rm arnavi5.o

# shared library for decode/encode Wialon IPS
wialonips: wialonips.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) wialonips.c -o wialonips.o
	$(CC) -shared -o wialonips.so wialonips.o
	rm wialonips.o

# shared library for decode/encode GPS-101 - GPS-103
gps103: gps103.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) gps103.c -o gps103.o
	$(CC) -shared -o gps103.so gps103.o
	rm gps103.o

# shared library for decode/encode SOAP
soap: soap.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) soap.c -o soap.o
	$(CC) -shared -o soap.so soap.o
	rm soap.o

# shared library for decode/encode EGTS
egts: egts.c egts.h de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) egts.c -o egts.o
	$(CC) -shared -o egts.so egts.o
	rm egts.o

# shared library for decode/encode FAVW
favw: favw.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) favw.c -o favw.o
	$(CC) -shared -o favw.so favw.o
	rm favw.o

# shared library for decode/encode FAVA
fava: fava.c de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) fava.c -o fava.o
	$(CC) -shared -o fava.so fava.o
	rm fava.o

# shared library for test/log protocol
prototest: prototest.c de.h glonassd.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) prototest.c -o prototest.o
	$(CC) -shared -o prototest.so prototest.o
	rm prototest.o

# shared library for database PostgreSQL
pg: pg.c glonassd.h de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) $(INCLUDE) -I/usr/include/postgresql pg.c $(LIBS) -o pg.o -lpq
	$(CC) -shared -o pg.so pg.o -lpq
	rm pg.o

# shared library for database REDIS
rds: rds.c glonassd.h de.h logger.h
	$(CC) -c $(SOCFLAGS) $(OPTIMIZE) $(INCLUDE) -I/usr/local/include/hiredis rds.c -I/usr/local/include/json-c/ $(LIBS) -o rds.o -lhiredis -ljson-c
	$(CC) -shared -o rds.so rds.o -lhiredis
	rm rds.o


# all
all: $(PROJECT) galileo satlite wialonips gps103 soap egts arnavi arnavi5 favw fava prototest pg rds

clean:
	rm -f *.o

```
